[env:rpipico]
platform = raspberrypi
board = rpipico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
upload_speed = 920600
monitor_filters = esp32_exception_decoder

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DUSBCON
    -DUSB_VID=0x2E8A
    -DUSB_PID=0x000A
